language: python

python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"

install:
    - pip install pipenv
    - pipenv install --dev

script: pipenv run nosetests --with-coverage --cover-package=pybib --cover-branches --rednose
