name: Python CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        version: 3.7
    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry
    - name: Install dependencies
      run: poetry install
    - name: Test with pytest
      run: poetry run pytest --cov=pybib --cov-branch
